spring.config.import=optional:file:.env

# Application
spring.application.name=MediFlow

# PostgreSQL : Connexion à la base de données PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# chaque fois que le serveur démarre, toutes les tables sont supprimées et recréées depuis zéro
spring.jpa.hibernate.ddl-auto=create
# Si true, affiche chaque requête SQL dans les logs. Utile pour déboguer, désactivé ici pour ne pas surcharger les logs.
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

# Server
# 8080
server.port=${SERVER_PORT} 

# CORS
# Autorise le frontend Angular (localhost:4200) à faire des requêtes vers le backend
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# AI Configuration (OpenRouter API)
app.ai.api-key=${API_kEY}
